name: Wake Up Render

on:
  schedule:
    # Run every 14 minutes
    - cron: '*/14 * * * *'

jobs:
  wake_app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping SchoolSync
        run: |
          curl -I https://schoolsync-3fnx.onrender.com         echo "Pinged Render App!"